### ISSUE TITLE
Properties are not deleted

### ISSUE THREAD

**Issue by franzlst** [plentymarkets/plentymarkets-shopware-connector#106] opened 2017-03-29 13:13 UTC
| Q                       | A
| ----------------------- | ---
| Bug?                    | yes
| Version                 | 2.0

#### Actual Behavior

When removing a property (Merkmal) of an article in plenty, it remains in Shopware

#### Expected Behavior

When removing a property (Merkmal) of an article in plenty, it should also be removed in Shopware.

#### Steps to Reproduce

This can be seen in our shop e.g. for article with ID 11. In plenty, the property "Amazon product_subtype" has been removed. In Shopware, it is still remaining (even after forcing a sync on that ID).

**Comment by jochenmanz** [comment] 2017-04-01 23:12
Hallo Franz,

i cannot reproduce your Problem. Could you test it again using the lasted development branch?

Best regards,
Jochen

**Comment by franzlst** [comment] 2017-04-02 18:29
Problem remains. All articles still habe the property "Amazon product_subtype" (Open any article in Shopware, go to "Eigenschaften").

**Comment by jochenmanz** [comment] 2017-04-03 07:47
Hallo Franz,

the backend is a bit misleading at this point. You are currently seeing all the available properties in the PlentyConnector group. The property "Amazon product_subtype" is only assigned to the product if a value is also present. 

Best regards,
Jochen

**Closed by jochenmanz** 2017-04-03 07:47 UTC
Labels: question

**Comment by franzlst** [comment] 2017-04-03 08:59
Ah, thank you!
